# use ubuntu18.04 with CUDA10.1 as base image
FROM nvidia/cuda:10.1-base-ubuntu18.04

# use anaconda3 latest version as base image
#FROM continuumio/anaconda3:latest


# install anaconda3 (dockerfile from continuumio/anaconda3
ENV LANG=C.UTF-8 LC_ALL=C.UTF-8
ENV PATH /opt/conda/bin:$PATH

RUN apt-get update --fix-missing && apt-get install -y wget bzip2 ca-certificates \
    libglib2.0-0 libxext6 libsm6 libxrender1 \
    git mercurial subversion

RUN wget --quiet https://repo.anaconda.com/archive/Anaconda3-2020.02-Linux-x86_64.sh -O ~/anaconda.sh && \
    /bin/bash ~/anaconda.sh -b -p /opt/conda && \
    rm ~/anaconda.sh && \
    ln -s /opt/conda/etc/profile.d/conda.sh /etc/profile.d/conda.sh && \
    echo ". /opt/conda/etc/profile.d/conda.sh" >> ~/.bashrc && \
    echo "conda activate base" >> ~/.bashrc

RUN apt-get install -y curl grep sed dpkg && \
    TINI_VERSION=`curl https://github.com/krallin/tini/releases/latest | grep -o "/v.*\"" | sed 's:^..\(.*\).$:\1:'` && \
    curl -L "https://github.com/krallin/tini/releases/download/v${TINI_VERSION}/tini_${TINI_VERSION}.deb" > tini.deb && \
    dpkg -i tini.deb && \
    rm tini.deb && \
    apt-get clean

ENTRYPOINT [ "/usr/bin/tini", "--" ]


# copy requirements file
COPY requirements.txt /project/
# set working directory
WORKDIR /project/


# install dependencies
RUN pip install -r requirements.txt

# copy the project
COPY . /project/

# open jupyter notebook
CMD jupyter-notebook --ip=0.0.0.0 --allow-root

# open bash terminal inside the container
# CMD /bin/bash
